GET http://localhost:5166/

###

POST http://localhost:5166/api/v1/categories
Content-Type: application/json

{
    "name" : "",
    "description": "This is good descriptions"
}

###

DELETE  http://localhost:5166/api/v1/categories/5699b6f3-1b2d-4dc0-b2d7-c75518bd092e

###

PUT   http://localhost:5166/api/v1/categories/c091a8da-70ca-4c20-a59c-70b606b5acdd
Content-Type: application/json

{
    "name" : "Feature Phones",
    "description" : "Dabba Phone is a nice categories"
}

###

GET    http://localhost:5166/api/v1/categories


###

GET    http://localhost:5166/api/v1/categories?searchValue=phone