GET http://localhost:5166/

###

POST http://localhost:5166/v1/api/categories
Content-Type: application/json

{
    "name" : "Dabba Phones",
    "description": "This is good descriptions"
}

###

DELETE  http://localhost:5166/v1/api/categories/84a412d4-d16f-4111-b8c9-c293a7c9ccf0
###

PUT   http://localhost:5166/v1/api/categories/84a412d4-d16f-4111-b8c9-c293a7c9ccf0
Content-Type: application/json

{
    "name" : "Feature Phones",
    "description": "This is good descriptions"
}

###

GET    http://localhost:5166/v1/api/categories

###

GET    http://localhost:5166/v1/api/categories/5fd840bc-aff4-4ef8-ba89-a26d7f99758b

